services:
  app:
    build: .
    ports:
      - 8080:8080
    container_name:
      deploy-maven-app
  nginx:
    image:
      nginx:mainline
    ports:
      - 81:81
    depends_on:
      - app
    container_name: deploy-maven-nginx
    volumes:
      - ./deploy-maven.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure
