services:
  app:
    build: .
    restart: on-failure
  nginx:
    image:
      nginx:mainline
    ports:
      - 8484:80
    depends_on:
      - app
    container_name: deploy-gradle-nginx
    volumes:
      - ./deploy-gradle.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure
   
