version: '3.9'
services:
  demo1:
    build: .
    restart: on-failure
    command: sh -c "python3 manage.py runserver 0.0.0.0:8000"
  nginx1:
    image: nginx:mainline
    ports:
      - "7000:80"
    volumes:
      - ./deploy-python.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - demo1
    
    restart: on-failure
