version: '3.9'
services:
  demo:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    command: sh -c "python3 manage.py runserver 0.0.0.0:8000"
  nginx:
    image: nginx:mainline
    ports:
      - "8088:80"
    volumes:
      - ./deploy-python.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - demo
    
    restart: on-failure
